export const testThrow = async function() {
    throw new Error('Mocked Error');
}